### ISSUE TITLE
Theano test performance

### ISSUE THREAD

**Issue by botev** [ilkarman/DeepLearningFrameworks#11]
I've just noticed your remark about the flags for test and train on Pytorch, Tensorflow. In fact, there is a similar thing for Lasagne which I totally forgot about. Could you change block 9 to:
```python
%%time
# Compile functions
train_func = theano.function([X.input_var, y], [loss, accuracy], updates=updates)
pred = L.get_output(net, deterministic=True)
pred_func = theano.function([X.input_var], T.argmax(pred, axis=1))
```

**Comment by miguelgfierro** [comment]
thanks @botev  we were just discussing this

**Comment by miguelgfierro** [comment]
0.779947916667 and 6min 46s

**Comment by ilkarman** [comment]
Perfect, I also get .78 on the K80! Thanks @botev
