### ISSUE TITLE
[what to do next] What problem you would like to see next?

### ISSUE THREAD

**Issue by miguelgfierro** [ilkarman/DeepLearningFrameworks#14]
We compared some of the top deep learning frameworks using CNNs and CIFAR. It would be great if the community could vote on what problem you would like to see next. I add some options:

- RNNs
- LSTMs on time series data
- LSTMs on text
- CNNs on ImageNet/bigger dataset
- CNNs on text
- Reinforcement Learning
- GANs/ VAC
- Neural art
- STOP DOING THIS, AI IS TOO DANGEROUS!!!
- Other??

cc @botev, @souptc, @YusukeSuzuki, @Yangqing, @ppwwyyxx, @miguelvr, @msalvaris, @ilkarman, @piiswrong, @soumith, @n17s

**Comment by ilkarman** [comment]
In this experiment we abstracted away from the performance of the native data generator. Although I suspect most will have this optimised very well to asynchronously handle IO loading from disk/database and applying data-augmentation other pre-processing on batches in some asychronous queue.

Would could be interesting is performance of custom layer (e.g. creating hierarchical softmax output) and differences in how multi-GPU gradient map-reduce is handled.

My vote is for a simple RNN on IMDB (embedding and then bi-directional LSTM/GRU) for sentiment

**Comment by miguelvr** [comment]
I would say RNNs are the next logical step (I would gladly contribute to it)

**Comment by miguelgfierro** [comment]
I agree with @miguelvr that RNNs is the natural step, however my vote goes to RL. I would be fun to replicate something like this https://gym.openai.com/envs/Humanoid-v1 :-)

**Comment by souptc** [comment]
I will vote for RNNs as next step, but RL is also very interesting.

**Comment by botev** [comment]
I would highly discourage RL for comparing the frameworks. RL on its own is quite picky and you might need to make various different choices in various frameworks. Not that it is not interesting, but unless you are really ready to put quite a bit of time in it I would not go into that.

As for the RNN, dependable on what is your goal I think there are 2 options:

1. Standard RNN/LSTM/GRU possibly stacked (usual user)
2. Implementing something slightly more funky to check how well do different framework optimise more non-standard recurrence cells (usual researcher) 

The actual choice of the problem - time series, audio, text - would be more for a nice show case than relevant for the framework comparison.

**Comment by miguelgfierro** [comment]
I think the winner is RNN/LSTM, makes a lot of sense. Thanks for your replies guys!
