### ISSUE TITLE
Chainer_CIFAR uses gpu without checking the "GPU" variable.

### ISSUE THREAD

**Issue by linmajia** [ilkarman/DeepLearningFrameworks#26]
data = cuda.to_gpu(data)
        target = cuda.to_gpu(target)

**Comment by miguelgfierro** [comment]
sorry, could you please explain a little bit better the issue? is there something wrong with the code?

**Comment by linmajia** [comment]
If we run it in CPU mode, the above 2 lines will throw exceptions.

**Comment by miguelgfierro** [comment]
Ok, thank you. I think we are going to support GPU for now, to make the code clearer.
