### ISSUE TITLE
Chainer implements Autotuner

### ISSUE THREAD

**Issue by Crissman** [ilkarman/DeepLearningFrameworks#34]
Ilia,

With the latest release of Chainer version 3.1, Chainer supports cuDNN auto-tuner for convolutional networks.

After installing Chainer v3.1, please add this line: `chainer.global_config.autotune = True` after the module imports to benchmark Chainer.

Here is our test run on AWS: https://github.com/unnonouno/DeepLearningFrameworks/blob/autotune/Chainer_CNN-autotune.ipynb

Please let me know if you have any issues with implementation.

Thanks!

**Comment by ilkarman** [comment]
That's great to see (@msalvaris)! Thank you, I will re-run the test.
