### ISSUE TITLE
Knet Inference

### ISSUE THREAD

**Issue by ilkarman** [ilkarman/DeepLearningFrameworks#35]
@kirnap @denizyuret Would it be possible at some point to directly compare the inference speed of Knet on a pre-trained resnet50 model similar to these [notebooks](https://github.com/ilkarman/DeepLearningFrameworks/tree/ikdev/inference)? 

I'm not sure if there is a converter for say caffe models to knet format?

The CNN and RNN training times are very impressive!

**Comment by denizyuret** [comment]
Sure,  we will look into this and get back to you. We already have a resnet
example in the repo but it may not be optimized for speed.


Did you figure out the JuliaPro installation or did you end up using Omer's
machine?

**Comment by ilkarman** [comment]
I installed the latest version of Julia and the packages (removing the older one installed by default on the VM). Timings were very close to Omer's image, well I ended up re-running everything (to standardise) on the 1 GPU machine (which has fewer CPU cores) so that dragged down timing by only a few seconds.
