### ISSUE TITLE
where I want to download the vm file?

### ISSUE THREAD

**Issue by xxccry** [ilkarman/DeepLearningFrameworks#41]
Hi @ilkarman ,
This project is such good. I want to download the vm file to run these deep learning framework, Can you share the download url? or I may buy the vm file. Thanks a lot

**Comment by ilkarman** [comment]
Hey xxccry, do you mean the VM Image file? This link ( https://azuremarketplace.microsoft.com/en-us/marketplace/apps/microsoft-ads.dsvm-deep-learning?tab=Overview ) should let you create one.
