### ISSUE TITLE
Extension to multi-GPU, multi-node

### ISSUE THREAD

**Issue by Crissman** [ilkarman/DeepLearningFrameworks#50]
@ilkarman Love the benchmarks.

It would be interesting to see which of the current platforms is able to scale the best to take advantage of cloud resources. Have you considered expanding to multi-GPU and to multi-node benchmarks?

**Comment by ilkarman** [comment]
@Crissman Thanks a lot for the comment! We are currently working on a significant update and looking at adding some bits from: on-the-fly data loader (with augmentation), data-parallel on multi-GPU (@msalvaris ), lower precision training.

**Comment by ilkarman** [comment]
@Crissman as a contributor (compared to say a user, like us) of Chainer is there anything specific you would like to see from benchmarks such as this? And also stuff that makes you roll your eyes instead? I think as a developer having your whole framework reduced to a timing for a basic CNN that calls cuDNN API would be a bit frustrating? Also misleading to new-starters who may like rankings but then asynchronous-queue data augmentation, data parallel training, ease of creating own layer, loaders to reduce disk read latency, integration with tensorboard, availability of pre-trained models, dynamic axes, inference-speed, mixed-precision training, quality of error-messages, community, model-compression utilities, exporting to coreML, ease of debug, and many others would all get missed. I think that the weighting is really user dependent so a ranking becomes meaningless, so instead have tried to focus on creating several different examples that explore different features and try to be standardised across frameworks. Curious if you agree

We definitely plan to multi-GPU

**Comment by Crissman** [comment]
@ilkarman Thanks for asking! As the major cloud providers ramp up their ML platforms, I think that multi-node (compared to multi-GPU) will become increasingly important, which is the reasoning behind the request.

The examples you're using are helpful. I feel they give a good overview of the time costs of different frameworks. In some cases, such as the application of cuDNN autotuning, the benchmarks have helped us to improve Chainer performance!

**Comment by ilkarman** [comment]
@Crissman Thanks again for your comments! We have started the effort to push multi-GPU examples with this PR - https://github.com/ilkarman/DeepLearningFrameworks/pull/53
