### ISSUE TITLE
MXNet MultiGPU

### ISSUE THREAD

**Issue by ilkarman** [ilkarman/DeepLearningFrameworks#88]
@ThomasDelteil I have been trying to re-run the [mxnet example](https://github.com/ilkarman/DeepLearningFrameworks/blob/mutligpuilia/notebooks/Gluon_MultiGPU.ipynb) on V100s, however still end up with the same error as on the P100s:

> MXNetError: [11:35:49] /home/travis/build/dmlc/mxnet-distro/mxnet-build/3rdparty/mshadow/mshadow/./stream_gpu-inl.h:62: Check failed: e == cudaSuccess CUDA: an illegal memory access was encountered

```
MXNet:  1.3.0
GPU:  ['Tesla V100-PCIE-16GB', 'Tesla V100-PCIE-16GB', 'Tesla V100-PCIE-16GB', 'Tesla V100-PCIE-16GB']
CUDA Version 9.0.176
CuDNN Version  7.0.5
```

Also do you know if any further updates on MXNet have reduced the need for the boiler-plate code e.g. "Hot fixing DataLoader for multi-processing and RecordFileDataset"? Also, perhaps to avoid using tfrecords and just the raw images as with the other frameworks? It would be cool to match the conciseness of other frameworks (e.g PyTorch)

**Comment by ilkarman** [comment]
@ThomasDelteil Thanks! The image download code in common/ now also does resize the images to 264 so the other frameworks just random-crop to 224 for training or resize to 224 for validation

**Comment by ThomasDelteil** [comment]
I see, that should make it easier them, I'll redownload the images then. The PyTorch dataset code worked almost as a drop-in in Gluon :+1:
