### ISSUE TITLE
Test Keras_CNTK with channel_first format

### ISSUE THREAD

**Issue by souptc** [ilkarman/DeepLearningFrameworks#9]
Current Keras_CNTK test case is running with channel_last format, which will led to perf degradation in cntk, that's why you see the warning:

/anaconda/envs/py35/lib/python3.5/site-packages/cntk/core.py:82: RuntimeWarning: data is not C contiguous; rearrange your data/computation to avoid costly data conversions
  RuntimeWarning)

Could we test with 'channel_first' format in keras? I manually run it on my box, Keras_CNTK is only around 20% slower than CNTK native implementation.

**Comment by ilkarman** [comment]
Thanks! This has actually made a big difference and I get similar results to yours. Will incorporate into master branch
